export const START_GET_PRODUCT = 'START_GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';

export const GET_PRODUCT_UPDATE = 'GET_PRODUCT_UPDATE';
